export const fontstyles = [
  {
    label: '',
    name: 'Helvetica',
    webStyles: { fontFamily: 'Helvetica' },
    canvasStyles: { fontFamily: 'Helvetica' },
  },
  {
    label: '',
    name: 'Adam Script',
    webStyles: { fontFamily: 'Adam Script' },
    canvasStyles: { fontFamily: 'Adam Script' },
  },
  {
    label: 'Attack Graffiti',
    name: 'Attack Graffiti',
    webStyles: { fontFamily: 'Attack Graffiti' },
    canvasStyles: { fontFamily: 'Attack Graffiti' },
  },
  {
    label: '',
    name: 'Bold Love',
    webStyles: { fontFamily: 'Bold Love' },
    canvasStyles: { fontFamily: 'Bold Love' },
  },
  {
    label: '',
    name: 'Bombing',
    webStyles: { fontFamily: 'Bombing' },
    canvasStyles: { fontFamily: 'Bombing' },
  },
  {
    label: '',
    name: 'Deutsch Gothic',
    webStyles: { fontFamily: 'Deutsch Gothic' },
    canvasStyles: { fontFamily: 'Deutsch Gothic' },
  },
  {
    label: '',
    name: 'Docallisme On Street',
    webStyles: {
      fontFamily: 'Docallisme On Street',
      textShadow: '5px 5px 5px rgba(0,0,0,0.5)',
    },
    canvasStyles: {
      fontFamily: 'Docallisme On Street',
      shadowColor: 'black',
      shadowBlur: 5,
      shadowOffsetX: 5,
      shadowOffsetY: 5,
      shadowOpacity: 0.5,
    },
  },
  {
    label: '',
    name: 'Geraldine',
    webStyles: { fontFamily: 'Geraldine' },
    canvasStyles: { fontFamily: 'Geraldine' },
  },
  {
    label: '',
    name: 'Menlawai',
    webStyles: { fontFamily: 'Menlawai' },
    canvasStyles: { fontFamily: 'Menlawai' },
  },
  {
    label: '',
    name: 'Mind The Caps',
    webStyles: { fontFamily: 'Mind The Caps' },
    canvasStyles: { fontFamily: 'Mind The Caps' },
  },
  {
    label: '',
    name: 'Next',
    webStyles: { fontFamily: 'Next' },
    canvasStyles: { fontFamily: 'Next' },
  },
  {
    label: '',
    name: 'Nose Grind',
    webStyles: { fontFamily: 'Nose Grind' },
    canvasStyles: { fontFamily: 'Nose Grind' },
  },
  {
    label: '',
    name: 'Peinture Fraiche',
    webStyles: { fontFamily: 'Peinture Fraiche' },
    canvasStyles: { fontFamily: 'Peinture Fraiche' },
  },
  {
    label: '',
    name: 'Sweet Unicorn',
    webStyles: {
      fontFamily: 'Sweet Unicorn',
      textShadow: '5px 5px 5px rgba(242,177,34, 1)',
    },
    canvasStyles: {
      fontFamily: 'Sweet Unicorn',
      shadowColor: 'rgb(242,177,34)',
      shadowBlur: 5,
      shadowOffsetX: 5,
      shadowOffsetY: 5,
      shadowOpacity: 1,
    },
  },
  {
    label: '',
    name: 'The Jacatra',
    webStyles: {
      fontFamily: 'The Jacatra',
      background: 'linear-gradient(45deg, red, blue)',
      WebkitTextFillColor: 'transparent',
      WebkitBackgroundClip: 'text',
      backgroundClip: 'text',
    },
    canvasStyles: {
      fontFamily: 'The Jacatra',
      fill: 'red',
      fillLinearGradientStartPoint: { x: 0, y: 0 },
      fillLinearGradientEndPoint: { x: 100, y: 100 },
      fillLinearGradientColorStops: [0, 'red', 1, 'blue'],
      fillEnabled: true,
      fillPriority: 'linear-gradient',
    },
  },
  {
    label: '',
    name: 'Throwupz',
    webStyles: { fontFamily: 'Throwupz' },
    canvasStyles: { fontFamily: 'Throwupz' },
  },
  {
    label: '',
    name: 'Waltograph',
    webStyles: { fontFamily: 'Waltograph' },
    canvasStyles: { fontFamily: 'Waltograph' },
  },
];
